// Starting draft, not legal advice — have a lawyer review before relying on
// this, especially the liability/AI-accuracy and governing-law sections.

export const metadata = { title: 'Terms of Service' };

export default function TermsPage() {
  return (
    <main className="page">
      <div className="page__head">
        <div>
          <h1>Terms of Service</h1>
          <p>Last updated: September 2026</p>
        </div>
      </div>
      <div className="stack" style={{ gap: 'var(--s-5)' }}>
        <section>
          <h2>Using Reclipse</h2>
          <p>
            By creating an account you agree to these terms. You must be at least 16 years old to use
            Reclipse. Keep your login credentials to yourself — you&apos;re responsible for activity on
            your account.
          </p>
        </section>

        <section>
          <h2>Your content</h2>
          <p>
            You own the notes, decks, flashcards, and quizzes you create. By uploading content, you
            give us permission to process it (including sending it to our AI provider) to generate
            your study materials. If you choose to make a deck public — sharing it, listing it on
            Discover (our public deck browser), or adding it to Campus Archive — other students will
            be able to see and study from it.
          </p>
          <p>
            Don&apos;t upload content you don&apos;t have the right to share, or anything that infringes
            someone else&apos;s copyright.
          </p>
        </section>

        <section>
          <h2>AI-generated content</h2>
          <p>
            Flashcards, quizzes, and study tips are generated by AI from the material you upload. They
            can contain mistakes. Reclipse is a study aid, not a substitute for your course materials —
            always check against what your instructor actually taught before an exam.
          </p>
        </section>

        <section>
          <h2>Campus Archive subscription</h2>
          <p>
            Campus Archive is a monthly subscription that unlocks every archived deck. See our{' '}
            <a href="/refund">Refund Policy</a> for how to cancel and what happens to billing when you do.
          </p>
        </section>

        <section>
          <h2>Referrals</h2>
          <p>
            If you refer a friend and they sign up using your code or link, you both get a reward once
            they become a paying Campus Archive subscriber: a discount off a future month, for both of
            you. Rewards are never cash and can&apos;t be redeemed for anything other than a Reclipse
            subscription discount.
          </p>
        </section>

        <section>
          <h2>Acceptable use</h2>
          <p>
            Don&apos;t use Reclipse to harass anyone, upload malicious files, attempt to access another
            student&apos;s account, or try to circumvent the daily/monthly generation limits (the caps
            on how many flashcard sets you can create) or payment system. We can suspend or terminate
            accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2>No warranty, limited liability</h2>
          <p>
            Reclipse is provided &quot;as is.&quot; We don&apos;t guarantee it will be error-free or
            available at all times. To the extent allowed by law, we aren&apos;t liable for indirect or
            consequential damages — for example, a bad grade or lost study time — arising from your
            use of the app, including exam outcomes based on AI-generated study material.
          </p>
        </section>

        <section>
          <h2>Changes</h2>
          <p>We may update these terms as the app changes. Continued use after an update means you accept the new terms.</p>
        </section>

        <section>
          <h2>Governing law</h2>
          <p>These terms are governed by the laws of Ontario, Canada.</p>
        </section>
      </div>
    </main>
  );
}
